name = "othellonia-tournament-site"
compatibility_date = "2026-02-22"
pages_build_output_dir = "src"

[[d1_databases]]
binding = "DB"
database_name = "othellonia_tournament_db"
database_id = "19cbd9bf-f1fa-4448-a773-e48fee2fc4c6"
